### ISSUE TITLE
RFC: Transparency

### ISSUE THREAD

**Issue by Keridos** [Donkie/SpoolmanDB#30]
We can currently only set translucent on filaments. However, PETG and especially PCTG are also offered as transparent.
Granted, it is not easy to print transparent prints, but they look different than translucent filaments.

Should a new flag called transparent be added?

**Comment by Donkie** [comment]
I think translucent is fine for this case as well. You can adjust the alpha of the hex if you want a detailed level of transparency shown. Could be set to 00 for fully transparent filaments for example.

**Comment by Keridos** [comment]
Thanks for the hint about the alpha channel, did not know that was possible, will use that instead.
