### ISSUE TITLE
Pulling info into Spoolman

### ISSUE THREAD

**Issue by limited660** [Donkie/SpoolmanDB#57]
Is there anything covering how to get these into the Spoolman instance? I've searched the spoolman docker install and cannot find where the json files are kept.

**Comment by ali86x** [comment]
Would be interested true. 
I did Not find a way to add the Data to spoolman.

**Comment by zacgoodwin** [comment]
When you add the filament or spool it has both an internal and external section. The external section pulls from this Github Repo

![image](https://github.com/user-attachments/assets/38408545-fc32-4e50-844e-c1015013631b)

![image](https://github.com/user-attachments/assets/71daf209-3a00-42ab-889b-94ad1e6aade7)

**Comment by ali86x** [comment]
Sometimes it could be so easy 😂

Thank you @zacgoodwin

**Comment by limited660** [comment]
Yes, very simple now that I see the button! Thank you.
